"""Add ref_no to transactions

Revision ID: 34a447ac7c1d
Revises: 43b3f7cb8eef
Create Date: 2025-06-23 19:16:57.036977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a447ac7c1d'
down_revision: Union[str, None] = '43b3f7cb8eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ref_no', sa.String(), nullable=True))
    op.alter_column('users', 'credits_remaining',
               existing_type=sa.INTEGER(),
               comment='Credits for PDF pages (1 credit = 1 page)',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'credits_remaining',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Credits for PDF pages (1 credit = 1 page)',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
    op.drop_column('transactions', 'ref_no')
    # ### end Alembic commands ###
