"""Add name and profile_picture to users

Revision ID: 5687c2b675ce
Revises: bfdbeb32d429
Create Date: 2025-06-12 17:12:23.106229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5687c2b675ce'
down_revision: Union[str, None] = 'bfdbeb32d429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('statements', sa.Column('file_id', sa.String(length=100), nullable=False))
    op.add_column('statements', sa.Column('format', sa.String(length=50), nullable=False))
    op.alter_column('statements', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_statements_file_id'), 'statements', ['file_id'], unique=True)
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.drop_column('statements', 'filename')
    op.add_column('transactions', sa.Column('balance', sa.Float(), nullable=True))
    op.alter_column('transactions', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_transactions_vendor'), table_name='transactions')
    op.create_index(op.f('ix_transactions_description'), 'transactions', ['description'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.drop_column('transactions', 'vendor')
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'name')
    op.add_column('transactions', sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_description'), table_name='transactions')
    op.create_index(op.f('ix_transactions_vendor'), 'transactions', ['vendor'], unique=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('transactions', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('transactions', 'balance')
    op.add_column('statements', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_file_id'), table_name='statements')
    op.alter_column('statements', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('statements', 'format')
    op.drop_column('statements', 'file_id')
    op.drop_column('statements', 'original_filename')
    # ### end Alembic commands ###
